//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientPortal.Resource.SurveyUser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PastSurvey {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PastSurvey() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PatientPortal.Resource.SurveyUser.PastSurvey", typeof(PastSurvey).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BacktoList {
            get {
                return ResourceManager.GetString("BacktoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Taken.
        /// </summary>
        public static string DateTaken {
            get {
                return ResourceManager.GetString("DateTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download PDF.
        /// </summary>
        public static string DownloadPDF {
            get {
                return ResourceManager.GetString("DownloadPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        public static string Guid {
            get {
                return ResourceManager.GetString("Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link To Survey.
        /// </summary>
        public static string LinkToSurvey {
            get {
                return ResourceManager.GetString("LinkToSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no any recommeded products..
        /// </summary>
        public static string NoProducts {
            get {
                return ResourceManager.GetString("NoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not completed any surveys..
        /// </summary>
        public static string NotCompletedSurvey {
            get {
                return ResourceManager.GetString("NotCompletedSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Surveys List.
        /// </summary>
        public static string PastSurveyList {
            get {
                return ResourceManager.GetString("PastSurveyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations.
        /// </summary>
        public static string Recommendations {
            get {
                return ResourceManager.GetString("Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Products.
        /// </summary>
        public static string RecommendedProducts {
            get {
                return ResourceManager.GetString("RecommendedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retake Survey.
        /// </summary>
        public static string RetakeSurvey {
            get {
                return ResourceManager.GetString("RetakeSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey ID.
        /// </summary>
        public static string SurveyID {
            get {
                return ResourceManager.GetString("SurveyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Link.
        /// </summary>
        public static string SurveyLink {
            get {
                return ResourceManager.GetString("SurveyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Name.
        /// </summary>
        public static string SurveyName {
            get {
                return ResourceManager.GetString("SurveyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Survey.
        /// </summary>
        public static string ViewSurvey {
            get {
                return ResourceManager.GetString("ViewSurvey", resourceCulture);
            }
        }
    }
}
